# Generated by Django 5.1.7 on 2025-10-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
