# Generated by Django 5.1.7 on 2025-12-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='dp',
            field=models.ImageField(blank=True, help_text='Optional display picture', null=True, upload_to='dp/'),
        ),
    ]
