# Generated by Django 5.1.7 on 2025-05-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Addons',
            field=models.ManyToManyField(blank=True, related_name='package_addon', to='events.packageaddon'),
        ),
    ]
