# Generated by Django 5.1.7 on 2025-05-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_booking_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(blank=True, choices=[('White Wedding', 'White Wedding'), ('Traditional Marriage', 'Traditional Marriage'), ('Prewedding Shoot', 'Prewedding Shoot'), ('', '')], max_length=255, null=True),
        ),
    ]
