# Generated by Django 5.1.7 on 2025-06-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
