# Generated by Django 5.1.7 on 2025-06-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_booking_amount_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageaddon',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_status',
            field=models.CharField(choices=[('Up Coming', 'Up Coming'), ('In progress', 'In progress'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='In progress', max_length=50),
        ),
    ]
