# Generated by Django 5.1.7 on 2025-06-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_packageaddon_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageAddOn',
            new_name='AddOn',
        ),
    ]
