# Generated by Django 5.1.7 on 2025-06-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_packageaddon_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='events.package'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
