# Generated by Django 5.1.7 on 2025-06-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_booking_packages_alter_booking_wedding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='wedding_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
