# Generated by Django 5.1.7 on 2025-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_booking_wedding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
