# Generated by Django 5.1.7 on 2025-06-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_booking_due_date_alter_booking_wedding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
