# Generated by Django 5.1.7 on 2025-06-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_booking_issue_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='unit_price',
            new_name='price',
        ),
    ]
