# Generated by Django 5.1.7 on 2025-07-03 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_invoiceitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='deliverables',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(blank=True, choices=[('White Wedding', 'White Wedding'), ('Traditional Marriage', 'Traditional Marriage'), ('Prewedding Shoot', 'Prewedding Shoot'), ('Others', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('package', 'Package'), ('addon', 'Add-On'), ('service', 'Additional Service'), ('discount', 'Discount'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='events.booking'),
        ),
    ]
