# Generated by Django 5.1.7 on 2025-08-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_invoiceitem_deliverables_alter_booking_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
