# Generated by Django 5.1.7 on 2025-08-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_booking_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='event_type',
            field=models.CharField(blank=True, choices=[('wedding', 'wedding'), ('burial', 'burial'), ('birthday', 'birthday'), ('corporate', 'coroprate'), ('custom', 'custom')], default='wedding', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(blank=True, choices=[('White Wedding', 'White Wedding'), ('Traditional Marriage', 'Traditional Marriage'), ('Prewedding Shoot', 'Prewedding Shoot'), ('Burial', 'Burial'), ('Birthday', 'Birthday'), ('Others', 'Others')], max_length=255, null=True),
        ),
    ]
