# Generated by Django 5.1.7 on 2025-09-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_package_event_type_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['price'], 'verbose_name': 'Event Package', 'verbose_name_plural': 'Event Packages'},
        ),
    ]
