# Generated by Django 5.1.7 on 2025-10-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Wedding', 'Wedding'), ('Traditional Marriage', 'Traditional Marriage'), ('Prewedding Shoot', 'Prewedding Shoot'), ('Burial', 'Burial'), ('Birthday', 'Birthday'), ('Others', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdate',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_dates', to='events.booking'),
        ),
    ]
