# Generated by Django 5.1.7 on 2025-11-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_booking_event_type_alter_bookingdate_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdate',
            name='date_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
