# Generated by Django 5.1.7 on 2025-03-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Package name (e.g., Gold, Platinum, Silver)', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Brief description of what the package includes')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the package in NGN', max_digits=10)),
                ('duration', models.CharField(help_text='Coverage duration (e.g., 6 hours, Full day)', max_length=50)),
                ('features', models.TextField(help_text='List of package features, separated by commas')),
                ('is_available', models.BooleanField(default=True, help_text='Is the package currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
