# Generated by Django 5.1.7 on 2025-04-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
