# Generated by Django 5.1.7 on 2025-06-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galleryimage_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='date_taken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
