# Generated by Django 5.1.7 on 2025-06-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_galleryimage_date_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='image',
            new_name='src',
        ),
    ]
