# Generated by Django 5.1.7 on 2025-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_rename_image_galleryimage_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('engagement', 'Engagement'), ('portrait', 'Portrait'), ('funeral', 'Funeral'), ('others', 'Others')], max_length=100),
        ),
    ]
