# Generated by Django 5.1.7 on 2025-05-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='brand_message',
            field=models.TextField(blank=True, help_text='A short inspiring message or slogan that represents your brand.'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='who_we_are',
            field=models.TextField(blank=True, help_text='A detailed description of your company, team, mission, or story.'),
        ),
    ]
