# Generated by Django 5.1.7 on 2025-05-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0002_alter_companyinfo_brand_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='bank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
